# Site settings
title: "Brad Dougherty - Resume"
description: "Senior Production Engineer | Site Reliability Engineer | Tech Enthusiast"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Brad Dougherty"
resume_title:                   "Senior Production Engineer | Site Reliability Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "brad@example.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(123) 456-7890"
resume_contact_address:         "Portland, OR"

resume_header_contact_info:     "Portland, OR • (123) 456-7890 • brad@example.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Experienced Production Engineer and Site Reliability Engineer with a passion for optimizing infrastructure, improving system reliability, and automating cloud deployments. Adept at leveraging DevOps best practices to enhance operational efficiency.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# Comment out sections you want to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
resume_social_links:
  resume_github_url:            "https://github.com/bradtaco"
  resume_linkedin_url:          "https://www.linkedin.com/in/yourlinkedin"
  resume_website_url:           "https://bradtaco.github.io"

resume_print_social_links:      true

# Design settings
resume_theme:                   default